### PR TITLE
Add file chunking and threading to improve performance

### PR DESCRIPTION
**Pull request by rsdunlapiv**
Adds the capability to read the trace in "chunks" of files (a chunk is a set of PETs) and the ability of the LoadBalance analysis to run with multiple threads.

The following default values have been defined for the parameters "chunksize" and "analysis_threading":
- `chunksize` = 250  (PETs at a time)
- `analysis_threading` = 1  (threads)

These default values are based on some empirical testing on a laptop and Hera as to values that seem to give the best performance when reading a trace.  Specifically, a large trace on Hera provided by @theurich has been reduced from over 30 minutes to about 6 minutes.

Most users will not need to set these values explicitly, although they can through a new command line argument `--xopts`.  For example, to set chunksize 500 and analysis threads to 4, use:

```
esmf-profiler  -t .... -o .... -n .... --xopts chunksize=500:analysis_threads=4
``` 

Changing chunksize and threading level should NOT change the output of the analysis.  Two new tests were added in `tests/test_main.py` to verify that output is the same under different chunksize and threading levels.

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
@ryanlong1004 this is ready for your review and testing

**Comment by ryanlong1004** [comment]
@rsdunlapiv 

I'm getting the error below when running your branch on Ubuntu 20.04.  If I switch to ```development``` branch, the script runs.

image

**Comment by rsdunlapiv** [comment]
@ryanlong1004 you need to point to a single trace:
./tests/fixtures/test-traces

should be:
tests/fixtures/test-traces/atm-ocn

It doesn't make sense to point the tool to a directory of multiple traces, because it can only process one at a time currently.

**Comment by ryanlong1004** [comment]
@rsdunlapiv That command works, but running it on test-traces-large does not.  That's the original large quantity of data we've been using from the start.

**Comment by ryanlong1004** [comment]
@rsdunlapiv OK, I don't remember having to specify the ```traceout``` folder before, but after I did, looks like it's humming away.

**Comment by rsdunlapiv** [comment]
@ryanlong1004 the prior approach to reading in the trace used an iterator that actually allowed you to have multiple traces -- it would traverse the subdirectories and find them all.  However, that doesn't really make any sense for the tool right now since we treat each trace separately  -- for example, there is no multi-trace view that would allow you to compare times.

Did you also push the fix to scripts/q.sh?

**Pull request merged**
