### PR TITLE
Feature dynamic chart options

### PR DESCRIPTION
**Pull request by ryanlong1004**
I'm pushing this through because it greatly increases the visibility and usability of the charts.

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
@ryanlong1004 if the chart key is moved to the right, can we also move the select all / select none to directly below the chart key?

**Comment by rsdunlapiv** [comment]
@ryanlong1004 using the latest development branch, I noticed that no matter what trace I process, it seems to be using this data file:
https://github.com/esmf-org/esmf-profiler/blob/development/web/app/build/data/load_balance.json

For example, if I run:
```
esmf-profiler -t tests/fixtures/test-traces/atm-ocn -o ./out -n out -s -v
```
which only has 4 PETs, I still see 1700 PETs in the profile.

Probably we should remove:
https://github.com/esmf-org/esmf-profiler/blob/development/web/app/build/data/load_balance.json
and
https://github.com/esmf-org/esmf-profiler/blob/development/web/app/build/data/site.json
entirely from the repo so they are not accidentally used.

**Comment by ryanlong1004** [comment]
> @ryanlong1004 if the chart key is moved to the right, can we also move the select all / select none to directly below the chart key?

Yes, it's in the works.  Looking into adding components _on top of_ a chart.

**Comment by ryanlong1004** [comment]
> @ryanlong1004 using the latest development branch, I noticed that no matter what trace I process, it seems to be using this data file: https://github.com/esmf-org/esmf-profiler/blob/development/web/app/build/data/load_balance.json
> 
> For example, if I run:
> 
> ```
> esmf-profiler -t tests/fixtures/test-traces/atm-ocn -o ./out -n out -s -v
> ```
> 
> which only has 4 PETs, I still see 1700 PETs in the profile.
> 
> Probably we should remove: https://github.com/esmf-org/esmf-profiler/blob/development/web/app/build/data/load_balance.json and https://github.com/esmf-org/esmf-profiler/blob/development/web/app/build/data/site.json entirely from the repo so they are not accidentally used.

If you ```git pull```, this should already be fixed in dev.

https://github.com/esmf-org/esmf-profiler/pull/133

**Pull request merged**
